/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionelib;

import static gestionelib.Login.Rights;
import static gestionelib.Login.Username;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Random; 


/**
 *
 * @author salvatorenitopi
 */
public class DeregistrazioneDipendente extends javax.swing.JFrame {
    
    
    String Username = "000";
    String Nome = null;
    String Cognome = null;
    String Telefono = null;
    String Email = null;
    String Indirizzo = null;
    int Rights = 3;



    /**
     * Creates new form Password
     */
    public DeregistrazioneDipendente() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Info_Label1 = new javax.swing.JLabel();
        First_Label = new javax.swing.JLabel();
        Username_Field = new javax.swing.JTextField();
        User_Label = new javax.swing.JLabel();
        Trova_Button = new javax.swing.JButton();
        Annulla_Button = new javax.swing.JButton();
        Info_Label = new javax.swing.JLabel();
        Username_Label = new javax.swing.JLabel();
        Telefono_Label = new javax.swing.JLabel();
        Email_Label = new javax.swing.JLabel();
        Indirizzo_Label = new javax.swing.JLabel();
        Cancella_Button = new javax.swing.JButton();
        Nome_Label = new javax.swing.JLabel();
        Cognome_Label = new javax.swing.JLabel();

        Info_Label1.setText("Utente *info*.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        First_Label.setText("Deregistrazione dipendente");

        Username_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Username_FieldActionPerformed(evt);
            }
        });
        Username_Field.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Username_FieldInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        Username_Field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Username_FieldKeyTyped(evt);
            }
        });

        User_Label.setText("Username");

        Trova_Button.setText("Trova");
        Trova_Button.setEnabled(false);
        Trova_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trova_ButtonActionPerformed(evt);
            }
        });

        Annulla_Button.setText("Annulla");
        Annulla_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annulla_ButtonActionPerformed(evt);
            }
        });

        Info_Label.setText("Inserisci username.");

        Username_Label.setText("Username: ");
        Username_Label.setEnabled(false);

        Telefono_Label.setText("Telefono: ");
        Telefono_Label.setEnabled(false);

        Email_Label.setText("Email: ");
        Email_Label.setEnabled(false);

        Indirizzo_Label.setText("Indirizzo: ");
        Indirizzo_Label.setEnabled(false);

        Cancella_Button.setText("Cancella");
        Cancella_Button.setEnabled(false);
        Cancella_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancella_ButtonActionPerformed(evt);
            }
        });

        Nome_Label.setText("Nome: ");
        Nome_Label.setEnabled(false);

        Cognome_Label.setText("Cognome:");
        Cognome_Label.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(User_Label)
                        .addGap(18, 18, 18)
                        .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Trova_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(First_Label)
                            .addComponent(Info_Label)
                            .addComponent(Username_Label)
                            .addComponent(Telefono_Label)
                            .addComponent(Email_Label)
                            .addComponent(Indirizzo_Label)
                            .addComponent(Nome_Label)
                            .addComponent(Cognome_Label))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cancella_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Annulla_Button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First_Label)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_Label)
                    .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Trova_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Info_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(Username_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cognome_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Telefono_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Indirizzo_Label)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancella_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Annulla_Button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Username_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Username_FieldActionPerformed
       
    }//GEN-LAST:event_Username_FieldActionPerformed

    private void Trova_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trova_ButtonActionPerformed
        resetPar ();
        trova ();

    }//GEN-LAST:event_Trova_ButtonActionPerformed

    private void Annulla_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annulla_ButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Annulla_ButtonActionPerformed

    private void Cancella_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancella_ButtonActionPerformed
        cancella ();
    }//GEN-LAST:event_Cancella_ButtonActionPerformed

    private void Username_FieldInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Username_FieldInputMethodTextChanged
         
    }//GEN-LAST:event_Username_FieldInputMethodTextChanged

    private void Username_FieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Username_FieldKeyTyped
         Trova_Button.setEnabled (true);
    }//GEN-LAST:event_Username_FieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeregistrazioneDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeregistrazioneDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeregistrazioneDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeregistrazioneDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeregistrazioneDipendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla_Button;
    private javax.swing.JButton Cancella_Button;
    private javax.swing.JLabel Cognome_Label;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JLabel First_Label;
    private javax.swing.JLabel Indirizzo_Label;
    private javax.swing.JLabel Info_Label;
    private javax.swing.JLabel Info_Label1;
    private javax.swing.JLabel Nome_Label;
    private javax.swing.JLabel Telefono_Label;
    private javax.swing.JButton Trova_Button;
    private javax.swing.JLabel User_Label;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JLabel Username_Label;
    // End of variables declaration//GEN-END:variables

    
    void resetPar (){
        
        Username = "000";
        Nome = null;
        Cognome = null;
        Telefono = null;
        Email = null;
        Indirizzo = null;
        
        Username_Label.setText ("Username: ");
        Nome_Label.setText ("Nome: ");
        Cognome_Label.setText ("Cognome: ");
        Telefono_Label.setText ("Telefono: ");
        Email_Label.setText ("Email: ");
        Indirizzo_Label.setText ("Indirizzo: ");
        
        Username_Label.setEnabled (false);
        Nome_Label.setEnabled (false);
        Cognome_Label.setEnabled (false);
        Telefono_Label.setEnabled (false);
        Email_Label.setEnabled (false);
        Indirizzo_Label.setEnabled (false);
                

        Cancella_Button.setEnabled (false);

        
        
    }
    
    
    public void trova (){
    
        
        resetPar ();
        
    
        if(!Username_Field.getText().isEmpty())  {
            
        
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                Statement stmt;
                // PreparedStatement pstmt;
                ResultSet rs;

                stmt = conn.createStatement();


                // recupero i dati
                rs = stmt.executeQuery("SELECT * FROM Utenti WHERE username='"+Username_Field.getText()+"' ");


                while(rs.next())
                {

                    if (!rs.getString("username").isEmpty()){
                        
                        Username = rs.getString("username");
                        Nome = rs.getString("nome");
                        Cognome = rs.getString("cognome");
                        Telefono = rs.getString("telefono");
                        Email = rs.getString("email");
                        Indirizzo = rs.getString("email");
                        Rights = rs.getInt("rights");
                    }
                }

                            //pstmt.close(); // rilascio le risorse
                            stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }


            if(!Username.equals("000"))  {

                Info_Label.setText ("Dipendente trovato:");
                
                Username_Label.setEnabled (true);
                Nome_Label.setEnabled (true);
                Cognome_Label.setEnabled (true);
                Telefono_Label.setEnabled (true);
                Email_Label.setEnabled (true);
                Indirizzo_Label.setEnabled (true);
                
                
                if (Rights == 1){
                Cancella_Button.setEnabled (true);
                }

                
                
                Username_Label.setText ("Username: "+Username);
                Nome_Label.setText ("Nome: "+Nome);
                Cognome_Label.setText ("Cognome: "+Cognome);
                Telefono_Label.setText ("Telefono: "+Telefono);
                Email_Label.setText ("Email: "+Email);
                Indirizzo_Label.setText ("Indirizzo: "+Indirizzo);
                
                
                
               

            }

            else {

                Info_Label.setText ("Dipendente non trovato");

            }
        
        }
        
        
        else {

                JOptionPane.showMessageDialog(null,"Campo Vuoto");

            }
                    

    } 
    
    public void sendSMS (String psw){
        
        // codice invio sms
        
    }
    
    public void sendEMAIL (String psw){
        
        // codice invio email
        
    }
    
    
    public void cancella (){
        
       
        

                try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                //Statement stmt;
                PreparedStatement pstmt;
                //ResultSet rs;

                // inserisco i record
                pstmt = conn.prepareStatement("DELETE FROM Utenti WHERE username='"+Username+"'");

  
                pstmt.execute();


                            pstmt.close(); // rilascio le risorse
                            //stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
              
                

        
        this.setVisible (false);
            
        JOptionPane.showMessageDialog(null,Username+", è stato cancellato");

        
    }

}
