/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionelib;

import static gestionelib.Login.Rights;
import static gestionelib.Login.Username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author salvatorenitopi
 */
public class GestioneNotifiche extends javax.swing.JFrame {
    
    String Telefono = null;
    String Email = null;
    int Notifiche = 2;

    /**
     * Creates new form GestioneNotifiche
     */
    public GestioneNotifiche() {
        initComponents();
        getPar ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        First_Label = new javax.swing.JLabel();
        Stato_Label = new javax.swing.JLabel();
        Stato2_Label = new javax.swing.JLabel();
        Indirizzo_Label = new javax.swing.JLabel();
        Telefono_Label = new javax.swing.JLabel();
        Attiva_Button = new javax.swing.JButton();
        Disattiva_Button = new javax.swing.JButton();
        Annulla_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        First_Label.setText("Gestione Notifiche");

        Stato_Label.setText("Attualmente ricevi le notifiche all'indirizzo:  ");

        Stato2_Label.setText("Attualmente ricevi le notifiche al numero:  ");

        Indirizzo_Label.setText("\\");

            Telefono_Label.setText("\\");

                Attiva_Button.setText("Attiva");
                Attiva_Button.setEnabled(false);
                Attiva_Button.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Attiva_ButtonActionPerformed(evt);
                    }
                });

                Disattiva_Button.setText("Disattiva");
                Disattiva_Button.setEnabled(false);
                Disattiva_Button.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Disattiva_ButtonActionPerformed(evt);
                    }
                });

                Annulla_Button.setText("Annulla");
                Annulla_Button.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        Annulla_ButtonActionPerformed(evt);
                    }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Stato2_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Telefono_Label))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Stato_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Indirizzo_Label))
                            .addComponent(First_Label))
                        .addContainerGap(160, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Attiva_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Disattiva_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Annulla_Button))
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(First_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Stato_Label)
                            .addComponent(Indirizzo_Label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Stato2_Label)
                            .addComponent(Telefono_Label))
                        .addGap(18, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Attiva_Button)
                            .addComponent(Disattiva_Button)
                            .addComponent(Annulla_Button)))
                );

                pack();
            }// </editor-fold>//GEN-END:initComponents

    private void Attiva_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Attiva_ButtonActionPerformed
        attivaNotifiche ();
        getPar ();
    }//GEN-LAST:event_Attiva_ButtonActionPerformed

    private void Annulla_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annulla_ButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Annulla_ButtonActionPerformed

    private void Disattiva_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Disattiva_ButtonActionPerformed
        disattivaNotifiche ();
        getPar ();
    }//GEN-LAST:event_Disattiva_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestioneNotifiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestioneNotifiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestioneNotifiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestioneNotifiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestioneNotifiche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla_Button;
    private javax.swing.JButton Attiva_Button;
    private javax.swing.JButton Disattiva_Button;
    private javax.swing.JLabel First_Label;
    private javax.swing.JLabel Indirizzo_Label;
    private javax.swing.JLabel Stato2_Label;
    private javax.swing.JLabel Stato_Label;
    private javax.swing.JLabel Telefono_Label;
    // End of variables declaration//GEN-END:variables


    public void getPar (){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
            Statement stmt;
            // PreparedStatement pstmt;
            ResultSet rs;
            
            stmt = conn.createStatement();


            // recupero i dati
            rs = stmt.executeQuery("SELECT * FROM Utenti WHERE username='"+Login.Username+"' ");


            while(rs.next())
            {
                
                if (!rs.getString("username").isEmpty()){
                    Telefono = rs.getString("telefono");
                    Email = rs.getString("email");
                    Notifiche = rs.getInt("notifiche");
                    
                }
            }

			//pstmt.close(); // rilascio le risorse
			stmt.close(); // rilascio le risorse
            conn.close(); // termino la connessione
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }
        
        
        // 0 = notifiche disattivate;
        // 1 = notifiche attivate;
        
        
        if(Notifiche == 1){
            Attiva_Button.setEnabled(false);
            Disattiva_Button.setEnabled(true);
            
            Stato_Label.setText ("Attualmente ricevi le notifiche all'indirizzo: ");
            Indirizzo_Label.setText (Email);
            Stato2_Label.setText ("Attualmente ricevi le notifiche al numero: ");
            Telefono_Label.setText (Telefono);
            
        }
        
        else {
            Attiva_Button.setEnabled(true);
            Disattiva_Button.setEnabled(false);
            Stato_Label.setText ("Attualmente non ricevi notifiche.");
            Indirizzo_Label.setText ("");
            Stato2_Label.setText ("");
            Telefono_Label.setText ("");
            
        }



    }
    
    public void attivaNotifiche (){
        
        
        try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                //Statement stmt;
                PreparedStatement pstmt;
                //ResultSet rs;

                // inserisco i record
                pstmt = conn.prepareStatement("UPDATE Utenti SET notifiche = '1' WHERE username='"+Login.Username+"'");

  
                pstmt.execute();


                            pstmt.close(); // rilascio le risorse
                            //stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
        
        
        
    }
    
    public void disattivaNotifiche (){
        
        
        try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                //Statement stmt;
                PreparedStatement pstmt;
                //ResultSet rs;

                // inserisco i record
                pstmt = conn.prepareStatement("UPDATE Utenti SET notifiche = '0' WHERE username='"+Login.Username+"'");

  
                pstmt.execute();


                            pstmt.close(); // rilascio le risorse
                            //stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
        
        
        
    }

}
