/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionelib;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author salvatorenitopi
 */
public class Login extends javax.swing.JFrame {
    
    public static int Rights = 2;
    
    public static String Username = "000";
    private String Password = null;
    
    private String usr = "";
    private String psw = "";

    /**
     * Creates new form Login
     */
    public Login() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2 - 127, dim.height/2-this.getSize().height/2 - 122);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Password_Field = new javax.swing.JPasswordField();
        Username_Field = new javax.swing.JTextField();
        First_Label = new javax.swing.JLabel();
        Second_Label = new javax.swing.JLabel();
        Username_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        Ok_button = new javax.swing.JButton();
        Quit_Button = new javax.swing.JToggleButton();
        RecuperaPsw_Button = new javax.swing.JButton();
        About_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        First_Label.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        First_Label.setText("Gestione Libreria");

        Second_Label.setText("Inserisci le tue credenziali");

        Username_Label.setText("Username");

        Password_Label.setText("Password");

        Ok_button.setText("OK");
        Ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ok_buttonActionPerformed(evt);
            }
        });

        Quit_Button.setText("Esci");
        Quit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quit_ButtonActionPerformed(evt);
            }
        });

        RecuperaPsw_Button.setText("Recupera Password");
        RecuperaPsw_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecuperaPsw_ButtonActionPerformed(evt);
            }
        });

        About_Button.setText("About");
        About_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Username_Label)
                                    .addComponent(Password_Label))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Username_Field)
                                    .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Second_Label)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(First_Label))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(About_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RecuperaPsw_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Quit_Button, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ok_button, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Second_Label)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ok_button, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(About_Button, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quit_Button)
                    .addComponent(RecuperaPsw_Button)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Quit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quit_ButtonActionPerformed
        
        JOptionPane.showMessageDialog(null,"Grazie per aver usato questo software");
        System.exit(0);
    }//GEN-LAST:event_Quit_ButtonActionPerformed

    private void Ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ok_buttonActionPerformed
        setParam();
        verificaCredenziali ();

    }//GEN-LAST:event_Ok_buttonActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void RecuperaPsw_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecuperaPsw_ButtonActionPerformed
      new Password().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_RecuperaPsw_ButtonActionPerformed

    private void About_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About_ButtonActionPerformed
        this.setVisible (false);
        new AboutLogin().setVisible(true);
    }//GEN-LAST:event_About_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_Button;
    private javax.swing.JLabel First_Label;
    private javax.swing.JButton Ok_button;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JToggleButton Quit_Button;
    private javax.swing.JButton RecuperaPsw_Button;
    private javax.swing.JLabel Second_Label;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JLabel Username_Label;
    // End of variables declaration//GEN-END:variables


    public void setParam()
    {
        usr = Username_Field.getText();

        psw = new String(Password_Field.getPassword());
    }

    
    public void verificaCredenziali (){
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
            Statement stmt;
            // PreparedStatement pstmt;
            ResultSet rs;
            
            stmt = conn.createStatement();


            // recupero i dati
            rs = stmt.executeQuery("SELECT * FROM Utenti WHERE username='"+usr+"' ");


            while(rs.next())
            {
                
                if (!rs.getString("username").isEmpty()){
                    Username = rs.getString("username");
                    Password = rs.getString("password");
                    Rights = rs.getInt ("rights");




                    System.out.println ("mysql "+Username);
                    System.out.println ("mysql "+Password);
                    System.out.println ("1)      " +Rights);
                }
            }

			//pstmt.close(); // rilascio le risorse
			stmt.close(); // rilascio le risorse
            conn.close(); // termino la connessione
        }
        catch(ClassNotFoundException e)
        {
            System.out.println(e);
        }
        catch(SQLException e)
        {
            System.out.println(e);
        }

        
        
        //System.out.println("Username - " + usr+"\n");
        
        if (Username.equals("000")){
            
            JOptionPane.showMessageDialog(null,"L'utente non esiste");
            
        }
            
        else{
            
            
            if(Username.equals(usr) && Password.equals(psw) )  {


                this.setVisible(false);
                message();
                new Menu().setVisible(true);
                
                //Caricamento loader = new Caricamento();
        
                //loader.exe ();



            }

            else {

                JOptionPane.showMessageDialog(null,"PASSWORD ERRATA");


            }
        
        } 
        
        
    }
    
    
    public void message (){
        
        if (Rights == 0){
            JOptionPane.showMessageDialog(null,"Benvenuto.\nHai effettuato l'accesso come Titolare");
          
        }
        
        else if (Rights == 1){
            
                JOptionPane.showMessageDialog(null,"Benvenuto.\nHai effettuato l'accesso come Dipendente");
           

            }
        
            else if (Rights == 2){
                
                JOptionPane.showMessageDialog(null,"Benvenuto.\nHai effettuato l'accesso come Utente");
               
            }
    }
    

}
