/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionelib;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author salvatorenitopi
 */
public class Menu extends javax.swing.JFrame {

    int NowRights = Login.Rights;

    /**
     * Creates new form Menu
     */
    public Menu() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2 - 127, dim.height/2-this.getSize().height/2 - 122);
        initComponents();
        setRights ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quit_Button = new javax.swing.JButton();
        First_Lablel = new javax.swing.JLabel();
        ModificaPsw_Button = new javax.swing.JButton();
        Bilancio_Button = new javax.swing.JButton();
        RegDip_Button = new javax.swing.JButton();
        InvioOrdine_Button = new javax.swing.JButton();
        Entrate_Button = new javax.swing.JButton();
        Uscite_Button = new javax.swing.JToggleButton();
        ModificaDip_Button = new javax.swing.JButton();
        CancellaDip_Button = new javax.swing.JButton();
        ContattaMagazino_Button = new javax.swing.JToggleButton();
        CreaOrdine_Button = new javax.swing.JButton();
        RegistraCliente_Button = new javax.swing.JButton();
        DeRegistraCliente_Button = new javax.swing.JButton();
        GestNotifiche_Button = new javax.swing.JButton();
        Pagamento_Button = new javax.swing.JToggleButton();
        Diritti_Label = new javax.swing.JLabel();
        TipoUtente_Label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        Logout_Button = new javax.swing.JButton();
        About_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Quit_Button.setText("Esci");
        Quit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quit_ButtonActionPerformed(evt);
            }
        });

        First_Lablel.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        First_Lablel.setText("Gestione Libreria");

        ModificaPsw_Button.setText("Modifica Password");
        ModificaPsw_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaPsw_ButtonActionPerformed(evt);
            }
        });

        Bilancio_Button.setText("Bilancio");
        Bilancio_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bilancio_ButtonActionPerformed(evt);
            }
        });

        RegDip_Button.setText("Registra Dip");
        RegDip_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegDip_ButtonActionPerformed(evt);
            }
        });

        InvioOrdine_Button.setText("Invio Ordine");
        InvioOrdine_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvioOrdine_ButtonActionPerformed(evt);
            }
        });

        Entrate_Button.setText("Entrate");
        Entrate_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrate_ButtonActionPerformed(evt);
            }
        });

        Uscite_Button.setText("Uscite");
        Uscite_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Uscite_ButtonActionPerformed(evt);
            }
        });

        ModificaDip_Button.setText("Modifica Dip");
        ModificaDip_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificaDip_ButtonActionPerformed(evt);
            }
        });

        CancellaDip_Button.setText("Cancella Dip");
        CancellaDip_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancellaDip_ButtonActionPerformed(evt);
            }
        });

        ContattaMagazino_Button.setText("Contatta Magazzino");
        ContattaMagazino_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContattaMagazino_ButtonActionPerformed(evt);
            }
        });

        CreaOrdine_Button.setText("Crea Ordine");
        CreaOrdine_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreaOrdine_ButtonActionPerformed(evt);
            }
        });

        RegistraCliente_Button.setText("Registra Cliente");
        RegistraCliente_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraCliente_ButtonActionPerformed(evt);
            }
        });

        DeRegistraCliente_Button.setText("Deregistra Cliente");
        DeRegistraCliente_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeRegistraCliente_ButtonActionPerformed(evt);
            }
        });

        GestNotifiche_Button.setText("Gestisci Notifiche");
        GestNotifiche_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestNotifiche_ButtonActionPerformed(evt);
            }
        });

        Pagamento_Button.setText("Pagamento");
        Pagamento_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pagamento_ButtonActionPerformed(evt);
            }
        });

        Diritti_Label.setText("Diritti:");

        TipoUtente_Label.setText("TipoUtente");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        Logout_Button.setText("Logout");
        Logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_ButtonActionPerformed(evt);
            }
        });

        About_Button.setText("About");
        About_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionelib/Logo/Book_logo.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(512, 512));
        jLabel1.setMinimumSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(First_Lablel)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GestNotifiche_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ModificaPsw_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Logout_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(About_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(Quit_Button))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Uscite_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ModificaDip_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(CancellaDip_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegDip_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Entrate_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bilancio_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ContattaMagazino_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DeRegistraCliente_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RegistraCliente_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CreaOrdine_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Pagamento_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InvioOrdine_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Diritti_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TipoUtente_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First_Lablel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Diritti_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TipoUtente_Label))
                        .addGap(37, 37, 37)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bilancio_Button)
                            .addComponent(CreaOrdine_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Entrate_Button)
                            .addComponent(ContattaMagazino_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Uscite_Button)
                            .addComponent(RegistraCliente_Button))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeRegistraCliente_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pagamento_Button)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RegDip_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ModificaDip_Button)
                                    .addComponent(InvioOrdine_Button))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancellaDip_Button))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GestNotifiche_Button)
                    .addComponent(About_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quit_Button)
                    .addComponent(ModificaPsw_Button)
                    .addComponent(Logout_Button))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Quit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quit_ButtonActionPerformed
       JOptionPane.showMessageDialog(null,"Grazie per aver usato questo software");
       System.exit(0);
    }//GEN-LAST:event_Quit_ButtonActionPerformed

    private void GestNotifiche_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestNotifiche_ButtonActionPerformed
        new GestioneNotifiche().setVisible (true);
    }//GEN-LAST:event_GestNotifiche_ButtonActionPerformed

    private void InvioOrdine_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvioOrdine_ButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Funzione momentaneamente non disponibile. Attendi la versione 3.0 del software ;-)");
    }//GEN-LAST:event_InvioOrdine_ButtonActionPerformed

    private void Bilancio_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bilancio_ButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Funzione momentaneamente non disponibile. Attendi la versione 3.0 del software ;-)");
    }//GEN-LAST:event_Bilancio_ButtonActionPerformed

    private void Entrate_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrate_ButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Funzione momentaneamente non disponibile. Attendi la versione 3.0 del software ;-)");
    }//GEN-LAST:event_Entrate_ButtonActionPerformed

    private void Uscite_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Uscite_ButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Funzione momentaneamente non disponibile. Attendi la versione 3.0 del software ;-)");
    }//GEN-LAST:event_Uscite_ButtonActionPerformed

    private void ModificaDip_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaDip_ButtonActionPerformed
        new ModificaDipendente().setVisible(true);
    }//GEN-LAST:event_ModificaDip_ButtonActionPerformed

    private void CancellaDip_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancellaDip_ButtonActionPerformed
        new DeregistrazioneDipendente().setVisible(true);
    }//GEN-LAST:event_CancellaDip_ButtonActionPerformed

    private void ModificaPsw_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificaPsw_ButtonActionPerformed
        this.setVisible(false);
        new ModificaPassword().setVisible(true);
    }//GEN-LAST:event_ModificaPsw_ButtonActionPerformed
           
    private void CreaOrdine_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreaOrdine_ButtonActionPerformed
        new CreaOrdine().setVisible(true); 
    }//GEN-LAST:event_CreaOrdine_ButtonActionPerformed

    private void ContattaMagazino_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContattaMagazino_ButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Funzione momentaneamente non disponibile. Attendi la versione 3.0 del software ;-)");
    }//GEN-LAST:event_ContattaMagazino_ButtonActionPerformed

    private void RegistraCliente_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraCliente_ButtonActionPerformed
        new RegistraCliente().setVisible(true);
    }//GEN-LAST:event_RegistraCliente_ButtonActionPerformed

    private void DeRegistraCliente_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeRegistraCliente_ButtonActionPerformed
        new DeregistrazioneCliente().setVisible(true);
    }//GEN-LAST:event_DeRegistraCliente_ButtonActionPerformed

    private void Pagamento_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pagamento_ButtonActionPerformed
        JOptionPane.showMessageDialog(null,"Funzione momentaneamente non disponibile. Attendi la versione 3.0 del software ;-)");
    }//GEN-LAST:event_Pagamento_ButtonActionPerformed

    private void RegDip_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegDip_ButtonActionPerformed
        new RegistraDipendente().setVisible(true);
    }//GEN-LAST:event_RegDip_ButtonActionPerformed

    private void Logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_ButtonActionPerformed
        logout ();
    }//GEN-LAST:event_Logout_ButtonActionPerformed

    private void About_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About_ButtonActionPerformed
        this.setVisible (false);
        new About().setVisible(true);
    }//GEN-LAST:event_About_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_Button;
    private javax.swing.JButton Bilancio_Button;
    private javax.swing.JButton CancellaDip_Button;
    private javax.swing.JToggleButton ContattaMagazino_Button;
    private javax.swing.JButton CreaOrdine_Button;
    private javax.swing.JButton DeRegistraCliente_Button;
    private javax.swing.JLabel Diritti_Label;
    private javax.swing.JButton Entrate_Button;
    private javax.swing.JLabel First_Lablel;
    private javax.swing.JButton GestNotifiche_Button;
    private javax.swing.JButton InvioOrdine_Button;
    private javax.swing.JButton Logout_Button;
    private javax.swing.JButton ModificaDip_Button;
    private javax.swing.JButton ModificaPsw_Button;
    private javax.swing.JToggleButton Pagamento_Button;
    private javax.swing.JButton Quit_Button;
    private javax.swing.JButton RegDip_Button;
    private javax.swing.JButton RegistraCliente_Button;
    private javax.swing.JLabel TipoUtente_Label;
    private javax.swing.JToggleButton Uscite_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables

    private void setRights (){
        
        
        
        // 0 Admin
        // 1 Dipendente
        // 2 Utente
        
        

       System.out.println ("2)      " +NowRights);
        
        if (NowRights == 0){
            //JOptionPane.showMessageDialog(null,"Benvenuto.\nHai effettuato l'accesso come Titolare");
            TipoUtente_Label.setText("Classe 0 - Titolare ("+Login.Username+")");
            
        }
        
        else if (NowRights == 1){
            
                //JOptionPane.showMessageDialog(null,"Benvenuto.\nHai effettuato l'accesso come Dipendente");
                TipoUtente_Label.setText("Classe 1 - Dipendente ("+Login.Username+")");

                Bilancio_Button.setEnabled(false);
                Entrate_Button.setEnabled(false);
                Uscite_Button.setEnabled(false);
                RegDip_Button.setEnabled(false);
                ModificaDip_Button.setEnabled(false);
                CancellaDip_Button.setEnabled(false);



            }
        
            else if (NowRights == 2){
                
                //JOptionPane.showMessageDialog(null,"Benvenuto.\nHai effettuato l'accesso come Utente");
                TipoUtente_Label.setText("Classe - 2 Utente ("+Login.Username+")");

                Bilancio_Button.setEnabled(false);
                Entrate_Button.setEnabled(false);
                Uscite_Button.setEnabled(false);
                RegDip_Button.setEnabled(false);
                ModificaDip_Button.setEnabled(false);
                CancellaDip_Button.setEnabled(false);
                
                CreaOrdine_Button.setEnabled(false);
                ContattaMagazino_Button.setEnabled(false);
                RegistraCliente_Button.setEnabled(false);
                DeRegistraCliente_Button.setEnabled(false);
                Pagamento_Button.setEnabled(false);
                InvioOrdine_Button.setEnabled(false);

            }
        
        
    }
    
    
    public void logout (){
        
        Login.Username = "000";
        this.setVisible (false);
        new Login ().setVisible (true);
        
    }

}




