/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionelib;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;



/**
 *
 * @author salvatorenitopi
 */
public class ModificaDipendente extends javax.swing.JFrame {
    
    String Username = "000";
    String Nome = null;
    String Cognome = null;
    String Telefono = null;
    String Email = null;
    String Indirizzo = null;
    int Rights = 3;

    /**
     * Creates new form RegistraDipendente
     */
    public ModificaDipendente() {
        initComponents();
        reset ();
        enabled (false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        First_Label = new javax.swing.JLabel();
        Nome_Label = new javax.swing.JLabel();
        Cognome_Label = new javax.swing.JLabel();
        Telefono_Label = new javax.swing.JLabel();
        Email_Label = new javax.swing.JLabel();
        Indirizzo_Label = new javax.swing.JLabel();
        Username_Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Email_Field = new javax.swing.JTextField();
        Telefono_Field = new javax.swing.JTextField();
        Cognome_Field = new javax.swing.JTextField();
        Nome_Field = new javax.swing.JTextField();
        Indirizzo_Field = new javax.swing.JTextField();
        Annulla_Button = new javax.swing.JToggleButton();
        Modifica_Button = new javax.swing.JButton();
        Username_Field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        First_Label.setText("Modifica dipendente");

        Nome_Label.setText("Nome");

        Cognome_Label.setText("Cognome");

        Telefono_Label.setText("Telefono");

        Email_Label.setText("E-Mail");

        Indirizzo_Label.setText("Indirizzo");

        Username_Label.setText("USERNAME");

        Nome_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nome_FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nome_Field, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addComponent(Cognome_Field)
            .addComponent(Telefono_Field)
            .addComponent(Email_Field)
            .addComponent(Indirizzo_Field)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(Nome_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cognome_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Telefono_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Email_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Indirizzo_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Annulla_Button.setText("Annulla");
        Annulla_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annulla_ButtonActionPerformed(evt);
            }
        });

        Modifica_Button.setText("Modifica");
        Modifica_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modifica_ButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Trova");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Annulla_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Modifica_Button)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(First_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email_Label)
                            .addComponent(Indirizzo_Label)
                            .addComponent(Telefono_Label)
                            .addComponent(Cognome_Label)
                            .addComponent(Nome_Label)
                            .addComponent(Username_Label))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First_Label)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username_Label)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Nome_Label)
                        .addGap(18, 18, 18)
                        .addComponent(Cognome_Label)
                        .addGap(18, 18, 18)
                        .addComponent(Telefono_Label)
                        .addGap(18, 18, 18)
                        .addComponent(Email_Label)
                        .addGap(18, 18, 18)
                        .addComponent(Indirizzo_Label)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Annulla_Button)
                    .addComponent(Modifica_Button)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Nome_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nome_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nome_FieldActionPerformed

    private void Modifica_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modifica_ButtonActionPerformed
        modifica ();
    }//GEN-LAST:event_Modifica_ButtonActionPerformed

    private void Annulla_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annulla_ButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_Annulla_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        trova ();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaDipendente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificaDipendente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Annulla_Button;
    private javax.swing.JTextField Cognome_Field;
    private javax.swing.JLabel Cognome_Label;
    private javax.swing.JTextField Email_Field;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JLabel First_Label;
    private javax.swing.JTextField Indirizzo_Field;
    private javax.swing.JLabel Indirizzo_Label;
    private javax.swing.JButton Modifica_Button;
    private javax.swing.JTextField Nome_Field;
    private javax.swing.JLabel Nome_Label;
    private javax.swing.JTextField Telefono_Field;
    private javax.swing.JLabel Telefono_Label;
    private javax.swing.JTextField Username_Field;
    private javax.swing.JLabel Username_Label;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
    public void trova (){
        
        reset ();
        enabled (false);
        getinfo ();
        
      
        
    }
    
    public void getinfo (){
        
        if(!Username_Field.getText().isEmpty())  {
            
        
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                Statement stmt;
                // PreparedStatement pstmt;
                ResultSet rs;

                stmt = conn.createStatement();


                // recupero i dati
                rs = stmt.executeQuery("SELECT * FROM Utenti WHERE username='"+Username_Field.getText()+"' ");


                while(rs.next())
                {

                    if (!rs.getString("username").isEmpty()){
                        
                        Username = rs.getString("username");
                        Nome = rs.getString("nome");
                        Cognome = rs.getString("cognome");
                        Telefono = rs.getString("telefono");
                        Email = rs.getString("email");
                        Indirizzo = rs.getString("indirizzo");
                        Rights = rs.getInt("rights");
                    }
                }

                            //pstmt.close(); // rilascio le risorse
                            stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
            
            
            
            
            
            
            if(!Username.equals("000"))  {
            
            enabled (true);
            Nome_Field.setText (Nome);
            Cognome_Field.setText (Cognome);
            Telefono_Field.setText (Telefono);
            Email_Field.setText (Email);
            Indirizzo_Field.setText (Indirizzo);
            
            if (Rights == 1){
                Modifica_Button.setEnabled (true);
                }
                
            }
            
            else {
            
            enabled (false);
            reset ();
            
            JOptionPane.showMessageDialog(null,"Dipendente non trovato");
            
            }
        
        }
        
        else {
            JOptionPane.showMessageDialog(null,"Inserisci username");
        }
        
    }

    

    
    void reset (){
        
        
        
        Nome_Field.setText ("");
        Cognome_Field.setText ("");
        Telefono_Field.setText ("");
        Email_Field.setText ("");
        Indirizzo_Field.setText ("");
        
        Username = "000";
        
        
    }
    
    public void enabled(boolean a){
        
        Nome_Label.setEnabled (a);
        Cognome_Label.setEnabled (a);
        Telefono_Label.setEnabled (a);
        Email_Label.setEnabled (a);
        Indirizzo_Label.setEnabled (a);
        
        Nome_Field.setEnabled (a);
        Cognome_Field.setEnabled (a);
        Telefono_Field.setEnabled (a);
        Email_Field.setEnabled (a);
        Indirizzo_Field.setEnabled (a);
        
        Modifica_Button.setEnabled (false);
        
    }
    
    public void modifica (){
        
        int status = 2;
                
        
        if (Nome_Field.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Il campo nome non può essere vuoto.");
            status = -1;
        }
        
        
        if (Cognome_Field.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Il campo cognome non può essere vuoto.");
            status = -1;
        }
        
        if (Email_Field.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Il campo email non può essere vuoto.");
            status = -1;
        }
        
        if (Indirizzo_Field.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Il campo indirizzo non può essere vuoto.");
            status = -1;
        }
        
        if (Username_Field.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Il campo username non può essere vuoto.");
            status = -1;
        }
        
        
        if (status == 2){
            
                try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                //Statement stmt;
                PreparedStatement pstmt;
                //ResultSet rs;


                // inserisco i record
                pstmt = conn.prepareStatement ("UPDATE Utenti SET nome = ?, cognome = ?, telefono = ?, email = ?, indirizzo = ? "
                        + "WHERE username='"+Username+"'");
                

                pstmt.setString(1, Nome_Field.getText());
                pstmt.setString(2, Cognome_Field.getText());

                pstmt.setString(3, Telefono_Field.getText());
                pstmt.setString(4, Email_Field.getText());
                pstmt.setString(5, Indirizzo_Field.getText());
                
                pstmt.execute();
                
                System.out.println (Nome_Field.getText()+Cognome_Field.getText()+Telefono_Field.getText() + Email_Field.getText()+Indirizzo_Field.getText());


                            pstmt.close(); // rilascio le risorse
                            //stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
            
                
               JOptionPane.showMessageDialog(null,"Dipendente modificato");
               this.setVisible(false);
    
        }
        
        else {
        JOptionPane.showMessageDialog(null,"Impossibile modificare dipendente");
        }
        
        
        
    }
       
    
    
}
