/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionelib;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author salvatorenitopi
 */
public class ModificaPassword extends javax.swing.JFrame {

    private String Vecchia_Password = null;
    private String Test_Password = "000";
    private String Nuova_Password = null;
    private String Verifica_Password = null;
    
    
    
    public ModificaPassword() {
        initComponents();
        Username_Label.setText (Login.Username+ " modifica la tua password.");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        First_Label = new javax.swing.JLabel();
        Username_Label = new javax.swing.JLabel();
        Vecchia_Label = new javax.swing.JLabel();
        Nuova_Label = new javax.swing.JLabel();
        Ripeti_Label = new javax.swing.JLabel();
        Password_Field = new javax.swing.JPasswordField();
        Nuova_Field = new javax.swing.JPasswordField();
        Ripeti_Field = new javax.swing.JPasswordField();
        OK_Button = new javax.swing.JButton();
        Annulla_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        First_Label.setText("Modifica Password");

        Username_Label.setText("*username* modifica la tua password.");

        Vecchia_Label.setText("Vecchia Password");

        Nuova_Label.setText("Nuova Password");

        Ripeti_Label.setText("Ripeti Password");

        OK_Button.setText("OK");
        OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_ButtonActionPerformed(evt);
            }
        });

        Annulla_Button.setText("Annulla");
        Annulla_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annulla_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(First_Label)
                            .addComponent(Username_Label)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Vecchia_Label)
                                    .addComponent(Nuova_Label)
                                    .addComponent(Ripeti_Label))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ripeti_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nuova_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(OK_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Annulla_Button)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username_Label)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vecchia_Label)
                    .addComponent(Password_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nuova_Label)
                    .addComponent(Nuova_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ripeti_Label)
                    .addComponent(Ripeti_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Annulla_Button)
                    .addComponent(OK_Button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Annulla_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annulla_ButtonActionPerformed
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_Annulla_ButtonActionPerformed

    private void OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_ButtonActionPerformed
        setPar ();
        modificaPassword ();
    }//GEN-LAST:event_OK_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificaPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla_Button;
    private javax.swing.JLabel First_Label;
    private javax.swing.JPasswordField Nuova_Field;
    private javax.swing.JLabel Nuova_Label;
    private javax.swing.JButton OK_Button;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JPasswordField Ripeti_Field;
    private javax.swing.JLabel Ripeti_Label;
    private javax.swing.JLabel Username_Label;
    private javax.swing.JLabel Vecchia_Label;
    // End of variables declaration//GEN-END:variables

    private void setPar (){
        
        
        Vecchia_Password = new String(Password_Field.getPassword());
        Nuova_Password = new String(Nuova_Field.getPassword());
        Verifica_Password = new String(Ripeti_Field.getPassword());

    }
    
    
    public void modificaPassword (){
        
        if (Nuova_Password.equals(Vecchia_Password)){
            
            JOptionPane.showMessageDialog(null,"La nuova password non può essere uguale a quella vecchia.");
            
        }
        
        else {
            if (!Nuova_Password.equals(Verifica_Password)){
                
                JOptionPane.showMessageDialog(null,"Le due password non corrispondono.");
                
            }
            else {
                
                try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                Statement stmt;
                // PreparedStatement pstmt;
                ResultSet rs;

                stmt = conn.createStatement();


                // recupero i dati
                rs = stmt.executeQuery("SELECT * FROM Utenti WHERE username='"+Login.Username+"' ");


                while(rs.next())
                {

                    //if (!rs.getString("username").isEmpty()){
                        Test_Password = rs.getString("password");

                    
                }

                            //pstmt.close(); // rilascio le risorse
                            stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
                
                
            
            
                if(!Test_Password.equals(Vecchia_Password))  {

                    JOptionPane.showMessageDialog(null,"La vecchia password è sbagliata.");

                }
                else {

                        try {
                        Class.forName("com.mysql.jdbc.Driver");
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                        //Statement stmt;
                        PreparedStatement pstmt;
                        //ResultSet rs;

                        // inserisco i record
                        pstmt = conn.prepareStatement("UPDATE Utenti SET password = '"+Nuova_Password+"' WHERE username='"+Login.Username+"'");


                        pstmt.execute();


                                    pstmt.close(); // rilascio le risorse
                                    //stmt.close(); // rilascio le risorse
                        conn.close(); // termino la connessione
                    }
                    catch(ClassNotFoundException e)
                    {
                        System.out.println(e);
                    }
                    catch(SQLException e)
                    {
                        System.out.println(e);
                    }

                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null,"La Password è stata modificata");
                    new Menu().setVisible(true);


                }
            
            }
            
        }
        
        
        
    }
    


}
