/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gestionelib;

import static gestionelib.Login.Rights;
import static gestionelib.Login.Username;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Random; 


/**
 *
 * @author salvatorenitopi
 */
public class Password extends javax.swing.JFrame {
    
    
    String Username = null;
    String Telefono = null;
    String Tel = "000";

    /**
     * Creates new form Password
     */
    public Password() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        First_Label = new javax.swing.JLabel();
        Telefono_Field = new javax.swing.JTextField();
        Telefono_Label = new javax.swing.JLabel();
        OK_Button = new javax.swing.JButton();
        Annulla_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        First_Label.setText("Recupero Password");

        Telefono_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Telefono_FieldActionPerformed(evt);
            }
        });

        Telefono_Label.setText("Telefono");

        OK_Button.setText("OK");
        OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_ButtonActionPerformed(evt);
            }
        });

        Annulla_Button.setText("Annulla");
        Annulla_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Annulla_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(First_Label)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Telefono_Label)
                        .addGap(18, 18, 18)
                        .addComponent(Telefono_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(OK_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Annulla_Button))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(First_Label)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono_Label)
                    .addComponent(Telefono_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Annulla_Button)
                    .addComponent(OK_Button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Telefono_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Telefono_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Telefono_FieldActionPerformed

    private void OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_ButtonActionPerformed
        setParam();
        verificaCredenziali ();

    }//GEN-LAST:event_OK_ButtonActionPerformed

    private void Annulla_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Annulla_ButtonActionPerformed
        this.setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_Annulla_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annulla_Button;
    private javax.swing.JLabel First_Label;
    private javax.swing.JButton OK_Button;
    private javax.swing.JTextField Telefono_Field;
    private javax.swing.JLabel Telefono_Label;
    // End of variables declaration//GEN-END:variables

    
    public void setParam()
    {
        Telefono = Telefono_Field.getText();
    }

    
    
    public void verificaCredenziali (){
    
        
    
        if(!Telefono.isEmpty())  {
            
        
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                Statement stmt;
                // PreparedStatement pstmt;
                ResultSet rs;

                stmt = conn.createStatement();


                // recupero i dati
                rs = stmt.executeQuery("SELECT * FROM Utenti WHERE telefono='"+Telefono+"' ");


                while(rs.next())
                {

                    if (!rs.getString("username").isEmpty()){
                        Tel = rs.getString("telefono");
                        Username = rs.getString("username");
                    }
                }

                            //pstmt.close(); // rilascio le risorse
                            stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }


            if(!Tel.isEmpty() && !Tel.equals("000"))  {

                nuovaPassword ();

            }

            else {

                JOptionPane.showMessageDialog(null,"Errore");

            }
        
        }
        
        
        else {

                JOptionPane.showMessageDialog(null,"Campo Vuoto");

            }
                    

} 

    
    public void sendSMS (String psw){
        
        // codice invio sms
        
    }
    
    public void sendEMAIL (String psw){
        
        // codice invio email
        
    }
    
    
    public void nuovaPassword (){
        
        Random rand = new Random();
        
        String psw1 = Integer.toString (rand.nextInt(10000));
        String psw2 = Integer.toString (rand.nextInt(10000));
        System.out.println (psw1 +"   "+ psw2);
        
        String password = psw1 + psw2;
        System.out.println ("Password: "+password);
        

                try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/Libreria?" + "user=root&password=");
                //Statement stmt;
                PreparedStatement pstmt;
                //ResultSet rs;

                // inserisco i record
                pstmt = conn.prepareStatement("UPDATE Utenti SET password = '"+password+"' WHERE telefono='"+Telefono+"'");

  
                pstmt.execute();


                            pstmt.close(); // rilascio le risorse
                            //stmt.close(); // rilascio le risorse
                conn.close(); // termino la connessione
            }
            catch(ClassNotFoundException e)
            {
                System.out.println(e);
            }
            catch(SQLException e)
            {
                System.out.println(e);
            }
              
                
        sendSMS (psw1);
        sendEMAIL (psw2);
        
        this.setVisible (false);
            
        JOptionPane.showMessageDialog(null,Username+", la tua password è stata resettata");
            
        new Login().setVisible(true);
        
    }

}
